blueprint:
  name: Cat Cam Motion → LLM → Multi-Notify (direct /media with custom buckets)
  domain: automation
  description: >
    On motion, wait for Ring eventId, download the clip to /config/media/ring_cams,
    analyze with LLMVision (snapshots in /config/media/llmvision), then notify multiple
    recipients with a snapshot and a tap-to-play video link. Works with multiple cameras
    (create one automation per cam). Uses your media_dirs keys: /media/llmvision and /media/ring.

  input:
    motion_binary_sensor:
      name: Motion Binary Sensor
      description: Motion sensor for this camera
      selector:
        entity:
          domain: binary_sensor

    event_select:
      name: Event Select (Ring)
      description: The select entity that exposes eventId + recordingUrl attributes
      selector:
        entity:
          domain: select

    notify_devices:
      name: Recipients (mobile_app devices)
      description: Phones to receive the notification
      selector:
        device:
          multiple: true
          filter:
            - integration: mobile_app

    provider_id:
      name: LLMVision Provider
      selector:
        config_entry:
          integration: llmvision

    subdir:
      name: Camera Subdirectory
      description: Folder under /config/media/ring_cams (e.g. cc, front, back)
      default: cc
      selector:
        text: {}

    cooldown_minutes:
      name: Cooldown (minutes)
      default: 10
      selector:
        number:
          min: 0
          max: 120
          mode: slider
          unit_of_measurement: min

mode: single

# -------- Variables --------
variables:
  event_select_entity: !input event_select
  provider: !input provider_id
  subdir: !input subdir

  # Per-second filename (you said same-second collisions won’t happen per camera)
  tstamp: "{{ now().strftime('%Y%m%dT%H%M%S') }}"
  filename: "{{ tstamp ~ '_motion.mp4' }}"

  # Absolute FS paths (where files actually live)
  ring_abs_base: /config/media/ring_cams
  llm_abs_base: /config/media/llmvision

  media_abs: "{{ ring_abs_base ~ '/' ~ subdir ~ '/' ~ filename }}"

  # Served URLs using YOUR media_dirs keys
  #   /config/media/ring_cams/...   -> /media/ring/...
  #   /config/media/llmvision/...   -> /media/llmvision/...
  media_rel: "{{ media_abs | replace('/config/media/ring_cams','/media/ring') }}"

  cam_name: >-
    {{ state_attr(event_select_entity, 'friendly_name')
       or state_attr(trigger.entity_id, 'friendly_name')
       or 'Camera' }}

trigger:
  - platform: state
    entity_id: !input motion_binary_sensor
    to: "on"

action:
  - alias: Wait for EventId to change
    wait_for_trigger:
      - platform: state
        entity_id: !input event_select
        attribute: eventId
    timeout: "00:05"

  - alias: Build Downloader Vars
    variables:
      recording_url: "{{ state_attr(event_select_entity, 'recordingUrl') | string }}"
      subdir_str: "{{ subdir | string }}"
      filename_str: "{{ filename | string }}"

  - alias: Download clip to /config/media/ring_cams
    service: downloader.download_file
    data:
      overwrite: false
      url: "{{ recording_url }}"
      subdir: "{{ subdir_str }}"
      filename: "{{ filename_str }}"

  - delay: "00:00:02"

  - alias: Analyze Video with LLMVision
    service: llmvision.video_analyzer
    response_variable: response
    data:
      provider: "{{ provider | string }}"
      video_file: "{{ media_abs }}"
      remember: true
      max_frames: 3
      target_width: 1280
      max_tokens: 1000
      generate_title: true
      expose_images: true
      message: >
        Summarize the events focusing only on moving subjects like people,
        vehicles, or animals. Ignore static objects. Keep it concise.
        If no movement is detected, respond with:
        'No activity observed. The response must be less than 255 characters.'

  - alias: Build Notification Vars
    variables:
      device_list: !input notify_devices

      # Map LLMVision keyframe to /media/llmvision/...
      keyframe_rel: >-
        {% set p = (response.key_frame | default('')) %}
        {% if p.startswith('/config/media/llmvision') %}
          {{ p.replace('/config/media/llmvision','/media/llmvision') }}
        {% elif p.startswith('/config/media/') %}
          {{ p.replace('/config/media/ring_cams','/media/ring') }}
        {% else %}
          {{ p.replace('/config','') }}
        {% endif %}

      # Video served as /media/ring/<subdir>/<file>.mp4
      video_rel: "{{ media_rel }}"

      message_text: "{{ response.response_text | default('No activity observed.') }}"

  - alias: Send Notification to Each Recipient
    repeat:
      for_each: "{{ device_list }}"
      sequence:
        - variables:
            service_name: >-
              {{ 'notify.mobile_app_' ~ (device_attr(repeat.item, 'name') | slugify) }}
        - service: "{{ service_name }}"
          data:
            title: "{{ cam_name }} — Motion Detected"
            message: "{{ message_text }}"
            data:
              # Thumbnail (use both mechanisms for cross-platform reliability)
              image: "{{ keyframe_rel }}"
              attachment:
                url: "{{ keyframe_rel }}"
                content-type: "jpeg"
              # Tap-to-play inside the HA app (relative URL)
              url: "{{ video_rel }}"
              clickAction: "{{ video_rel }}"

  - alias: Cooldown Before Retrigger
    delay:
      minutes: !input cooldown_minutes
