blueprint:
  name: Cat Cam Motion → LLM → Multi-Notify (HQ GIF preview, image only)
  domain: automation
  description: >
    On motion, wait for Ring eventId, download the clip to /config/media/ring_cams,
    analyze with LLMVision, render a high-quality GIF preview to /config/www (served as /local),
    then notify multiple recipients with the animated GIF thumbnail (image: only).
    Create one automation per camera.

  input:
    motion_binary_sensor:
      name: Motion Binary Sensor
      description: Motion sensor for this camera
      selector:
        entity:
          domain: binary_sensor

    event_select:
      name: Event Select (Ring)
      description: The select entity that exposes eventId + recordingUrl attributes
      selector:
        entity:
          domain: select

    notify_devices:
      name: Recipients (mobile_app devices)
      description: Phones to receive the notification
      selector:
        device:
          multiple: true
          filter:
            - integration: mobile_app

    provider_id:
      name: LLMVision Provider
      selector:
        config_entry:
          integration: llmvision

    subdir:
      name: Camera Subdirectory (under ring_cams/)
      description: Folder name for this camera (e.g. cc, front, back)
      default: cc
      selector:
        text: {}

    # ---- GIF quality controls ----
    gif_start:
      name: GIF Start Offset (s)
      description: Skip a bit to avoid camera wake blur (0–1s is common)
      default: 0
      selector:
        number:
          min: 0
          max: 3
          step: 0.1
          mode: slider
          unit_of_measurement: s

    gif_duration:
      name: GIF Duration (seconds)
      default: 5
      selector:
        number:
          min: 1
          max: 8
          step: 1
          mode: slider
          unit_of_measurement: s

    gif_fps:
      name: GIF FPS
      default: 8
      selector:
        number:
          min: 4
          max: 15
          step: 1
          mode: slider
          unit_of_measurement: fps

    gif_width:
      name: GIF Width (pixels)
      default: 480
      selector:
        number:
          min: 240
          max: 640
          step: 10
          mode: slider
          unit_of_measurement: px

    gif_colors:
      name: GIF Palette Colors
      description: 128 is a great balance; 256 = highest quality, bigger files
      default: 128
      selector:
        number:
          min: 32
          max: 256
          step: 32
          mode: slider

    gif_dither:
      name: GIF Dithering
      description: sierra2_4a (best), bayer (smaller), floyd_steinberg (punchy)
      default: sierra2_4a
      selector:
        select:
          options:
            - sierra2_4a
            - bayer
            - floyd_steinberg

    cooldown_minutes:
      name: Cooldown (minutes)
      default: 10
      selector:
        number:
          min: 0
          max: 120
          mode: slider
          unit_of_measurement: min

mode: single

# -------- Variables --------
variables:
  event_select_entity: !input event_select
  provider: !input provider_id
  subdir: !input subdir

  # Per-second filename (you said collisions aren’t a concern)
  tstamp: "{{ now().strftime('%Y%m%dT%H%M%S') }}"
  filename_mp4: "{{ tstamp ~ '_motion.mp4' }}"
  filename_gif: "{{ tstamp ~ '_motion.gif' }}"

  # Absolute FS paths
  ring_abs_base: /config/media/ring_cams
  www_abs_base: /config/www/ring_cams

  media_abs: "{{ ring_abs_base ~ '/' ~ subdir ~ '/' ~ filename_mp4 }}"
  gif_abs_dir: "{{ www_abs_base ~ '/' ~ subdir }}"
  gif_abs: "{{ gif_abs_dir ~ '/' ~ filename_gif }}"

  # Served URLs (you have media_dirs keys: ring, llmvision)
  video_rel: "{{ media_abs | replace('/config/media/ring_cams','/media/ring') }}"
  gif_rel: "{{ gif_abs | replace('/config/www','/local') }}"

  cam_name: >-
    {{ state_attr(event_select_entity, 'friendly_name')
       or state_attr(trigger.entity_id, 'friendly_name')
       or 'Camera' }}

trigger:
  - platform: state
    entity_id: !input motion_binary_sensor
    to: "on"

action:
  - alias: Wait for EventId to change
    wait_for_trigger:
      - platform: state
        entity_id: !input event_select
        attribute: eventId
    timeout: "00:05"

  - alias: Build Downloader Vars
    variables:
      recording_url: "{{ state_attr(event_select_entity, 'recordingUrl') | string }}"
      subdir_str: "{{ subdir | string }}"
      filename_mp4_str: "{{ filename_mp4 | string }}"

  - alias: Download clip to /config/media/ring_cams
    service: downloader.download_file
    data:
      overwrite: false
      url: "{{ recording_url }}"
      subdir: "{{ subdir_str }}"
      filename: "{{ filename_mp4_str }}"

  - delay: "00:00:02"

  - alias: Analyze Video with LLMVision
    service: llmvision.video_analyzer
    response_variable: response
    data:
      provider: "{{ provider | string }}"
      video_file: "{{ media_abs }}"
      remember: true
      max_frames: 3
      target_width: 1280
      max_tokens: 1000
      generate_title: true
      expose_images: true
      message: >
        Summarize the events focusing only on moving subjects like people,
        vehicles, or animals. Ignore static objects. Keep it concise.
        If no movement is detected, respond with:
        'No activity observed. The response must be less than 255 characters.'

  # -------- Create HQ GIF preview under /www (/local) --------
  - alias: Ensure /config/www/ring_cams/<subdir> exists
    service: shell_command.ensure_dir
    data:
      dir: "{{ gif_abs_dir }}"

  - alias: Render HQ GIF with ffmpeg (palettegen + paletteuse)
    service: shell_command.make_motion_gif_hq
    data:
      input: "{{ media_abs }}"
      output: "{{ gif_abs }}"
      start: !input gif_start
      duration: !input gif_duration
      fps: !input gif_fps
      width: !input gif_width
      colors: !input gif_colors
      dither: !input gif_dither

  # -------- Build notification vars --------
  - alias: Build Notification Vars
    variables:
      device_list: !input notify_devices
      message_text: "{{ response.response_text | default('No activity observed.') }}"
      # Show & tap the GIF (simple, zero-auth friction)
      image_rel: "{{ gif_rel }}"
      tap_rel: "{{ gif_rel }}"
      # If you later want tap to open the MP4 instead:
      # tap_rel: "{{ video_rel }}"

  # -------- Notify each selected device --------
  - alias: Send Notification to Each Recipient
    repeat:
      for_each: "{{ device_list }}"
      sequence:
        - alias: Build per-device notify service name
          variables:
            service_name: >-
              {{ 'notify.mobile_app_' ~ (device_attr(repeat.item, 'name') | slugify) }}

        - alias: Send to device
          service: "{{ service_name }}"
          data:
            title: "{{ cam_name }} — Motion Detected"
            message: "{{ message_text }}"
            data:
              image: "{{ image_rel }}"
              url: "{{ tap_rel }}"
              clickAction: "{{ tap_rel }}"

  - alias: Cooldown Before Retrigger
    delay:
      minutes: !input cooldown_minutes
